name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Create storage_state.json
      run: |
        mkdir -p auto_collect
        echo '{}' > auto_collect/storage_state.json
        
    - name: Build executable
      run: python build.py
      
    - name: Package for release (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd dist
        7z a -tzip ../AutoCollect-Windows-${{ github.ref_name }}.zip AutoCollect/
        
    - name: Package for release (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd dist
        zip -r ../AutoCollect-macOS-${{ github.ref_name }}.zip AutoCollect/ AutoCollect.app/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AutoCollect-*.zip
        body: |
          ## AutoCollect ${{ github.ref_name }}
          
          ### 新功能和改进
          - 跨平台支持 (Windows & macOS)
          - 自动化构建和发布
          - 完整的数据库管理界面
          - 优化的用户体验
          
          ### 下载说明
          - **Windows 用户**: 下载 `AutoCollect-Windows-${{ github.ref_name }}.zip`
          - **macOS 用户**: 下载 `AutoCollect-macOS-${{ github.ref_name }}.zip`
          
          ### 安装方法
          1. 下载对应平台的压缩包
          2. 解压到任意位置
          3. 运行可执行文件
          
          ### 系统要求
          - Windows 10 或更高版本
          - macOS 10.14 或更高版本
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}